```yaml
server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            # =========================
            # ALUMNO
            # =========================
            - id: alumnos
              uri: lb://MS-ALUMNOS
              predicates:
                - Path=/api/alumnos/**

            # =========================
            # ADMINISTRACION
            # =========================
            - id: administracion
              uri: lb://ADMINISTRACION
              predicates:
                - Path=/api/administracion/**

            # =========================
            # CURSOS
            # =========================
            - id: cursos
              uri: lb://CURSOS
              predicates:
                - Path=/api/cursos/**

            # =========================
            # SWAGGER ALUMNO
            # =========================
            - id: swagger-alumnos
              uri: lb://MS-ALUMNOS
              predicates:
                - Path=/alumnos/swagger-ui/**

            # =========================
            # SWAGGER ADMINISTRACION
            # =========================
            - id: swagger-administracion
              uri: lb://ADMINISTRACION
              predicates:
                - Path=/administracion/swagger-ui/**

            # =========================
            # SWAGGER CURSOS
            # =========================
            - id: swagger-cursos
              uri: lb://CURSOS
              predicates:
                - Path=/cursos/swagger-ui/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    lease-renewal-interval-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
```
