server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:C:/Users/Oscar/eclipse-workspace/Proyektos/school-microservicios/data/escuela;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
